### ISSUE TITLE
Example shapefiles failed to load

### ISSUE THREAD

**Issue by olehprylutskyi** [olehprylutskyi/spectralR#10]
Example shapefile filed to load via

`sf_df <- prepare.vector.data(system.file("extdata/test_shapefile.shp", package = "spectralR"), "veget_type")`

with an error message:

> Error: `dsn` must point to a source, not an empty string

 regardless using either RMarkdown or regular R script. Presumably `path` error.

**Comment by vmikk** [comment]
This issue was fixed.
