### ISSUE TITLE
spectral.curves.plot doesn't work after specifying smother

### ISSUE THREAD

**Issue by olehprylutskyi** [olehprylutskyi/spectralR#6]
After recent pull request https://github.com/olehprylutskyi/spectralR/pull/5/commits/ba418f937c0ebc05333c983efaac0233713cd1bd `spectral.curves.plot` function stopped working - returned empty background instead of a plot. @vmikk #5

**Comment by vmikk** [comment]
Hmm, my bad. Will fix it ASAP.
It's because of `formula = y ~ s(x, bs = "cs")`

**Comment by olehprylutskyi** [comment]
PR merged, everything works fine
